name: Test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Installing dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Running tests
        run: yarn test:all
